apiVersion: policy.networking.k8s.io/v1alpha1
kind: AdminNetworkPolicy
metadata:
  name: anp-pod-selector-allow-ingress-restricted-from-open-p12
spec:
  priority: 12
  subject:
    pods:
      namespaceSelector:
        matchLabels:
          anplabel: anp-restricted
      podSelector:
        matchLabels:
          anplabel: anp-restricted
  ingress:
  - name: "allow-all-ingress-from-anp-open"
    action: "Allow"
    from:
    - pods:
        namespaceSelector:
          matchLabels:
            anplabel: anp-open
        podSelector:
          matchLabels:
            anplabel: anp-open
  egress:
  - name: "deny-all-egress-to-anp-open"
    action: "Deny"
    to:
    - pods:
        namespaceSelector:
          matchLabels:
            anplabel: anp-open
        podSelector:
          matchLabels:
            anplabel: anp-open
